# Generated by Django 2.0.3 on 2018-03-17 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateID', models.IntegerField()),
                ('certificatetype', models.CharField(choices=[('Fitness', 'Fitness'), ('Insurance', 'Insurance'), ('Pollution', 'Pollution')], max_length=15)),
                ('certificateIssueDate', models.DateField(default=datetime.date.today)),
                ('certificateExpiryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverVerficationID', models.IntegerField(max_length=12)),
                ('driverName', models.CharField(max_length=50)),
                ('driverPhoneNumber', models.IntegerField(max_length=10)),
                ('driverAddress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Holds_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Globals.Certificates')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckNumber', models.CharField(max_length=15)),
                ('driverName', models.CharField(max_length=50)),
                ('certificateType', models.CharField(choices=[('Fitness', 'Fitness'), ('Insurance', 'Insurance'), ('Pollution', 'Pollution')], max_length=15)),
                ('daysLeft', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckNumber', models.CharField(max_length=15)),
                ('driverID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='Globals.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='holds_certificate',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Globals.Truck'),
        ),
    ]
