# Generated by Django 2.0.3 on 2018-03-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='certificatetype',
            new_name='certificateType',
        ),
        migrations.AlterField(
            model_name='holds_certificate',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='Globals.Truck'),
        ),
    ]
