# Generated by Django 2.0.3 on 2018-03-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0002_auto_20180317_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holds_certificate',
            old_name='certificates',
            new_name='certificate',
        ),
    ]
