# Generated by Django 2.0.3 on 2018-03-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0003_auto_20180317_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='daysLeft',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
